name: EcoKill
main: io.github.rsmake.EcoKill.Eco
version: 1.2
author: RSmake
depend: [Vault]

commands:
  ecoreload:
    description: Reload the EcoKill Plugin
    usage: /ecoreload

permissions:
  ecokill.reload:
    description: Allows you to reload the EcoKill plugin.
    default: op